{
 "title": "Backend – Golden Signals",
 "time": { "from": "2025-12-28T13:30:37.768Z", "to": "2025-12-28T15:23:24.863Z" },
 "panels": [
  {
   "title": "Backend availability",
   "type": "stat",
   "description": "Is Backend UP or DOWN",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency – p95",
   "type": "timeseries",
   "description": "How slow are requests for users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "seconds (s)" } },
   "targets": [
    {
     "expr": "histogram_quantile(   0.95,   rate(backend_request_duration_seconds_bucket[5m]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Is backend leaking memory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes (IEC)" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Traffic – Requests per second",
   "type": "timeseries",
   "description": "How much traffic is the backend receiving?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{endpoint}}" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "Is backend under CPU pressure",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors – 5xx rate",
   "type": "timeseries",
   "description": "Are users seeing errors",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "req/s" } },
   "targets": [
    {
     "expr": "rate(sum(rate(http_requests_total{status=~\"5..\"}[1m])) or vector(0){status=~\"5..\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}